### ISSUE TITLE
On mysqldb 1.2.3 getting attribute error: 'Connection' object has no attribute 'get_autocommit'

### ISSUE THREAD

**Issue by moshe742** [farcepest/MySQLdb1#115]
I am trying to work with specify which is working with mysqldb package version 1.2.3, but when I try to get tothe first page I get the error in the title.
I saw that the Connection class should have a function get_autocommit (on line 260 in connections.py for example) but I can't find it in the class OR the class Connection is inheriting from.

Please help.
Thanks.
Moshe
